# Generated by Django 5.2.4 on 2025-07-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indicador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submenu", models.CharField(max_length=50)),
                ("periodo", models.CharField(max_length=10)),
                ("mes", models.CharField(blank=True, max_length=20, null=True)),
                ("porcentaje", models.FloatField()),
                ("analisis_datos", models.TextField(blank=True, null=True)),
                ("analisis_causas", models.TextField(blank=True, null=True)),
                ("num_no_utilizadas", models.IntegerField(blank=True, null=True)),
                ("total_disponibles", models.IntegerField(blank=True, null=True)),
                ("num_sin_novedad", models.IntegerField(blank=True, null=True)),
                ("total_despachos", models.IntegerField(blank=True, null=True)),
                ("sum_no_retorno", models.IntegerField(blank=True, null=True)),
                ("num_entregados_tiempo", models.IntegerField(blank=True, null=True)),
                (
                    "total_servicios_prestados",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_vehiculos_solicitados",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_vehiculos_fuera_programacion",
                    models.IntegerField(blank=True, null=True),
                ),
                ("num_vehiculos_fallas", models.IntegerField(blank=True, null=True)),
                (
                    "num_vehiculos_solicitados_mes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_conductores_arqueo_mes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_conductores_novedad_arqueo",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_servicios_flota_propia",
                    models.IntegerField(blank=True, null=True),
                ),
                ("num_total_servicios", models.IntegerField(blank=True, null=True)),
                (
                    "num_mantenimientos_preventivos",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_mantenimientos_predictivos",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_mantenimientos_correctivos",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_mantenimientos_pendientes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_mantenimientos_cumplidos",
                    models.IntegerField(blank=True, null=True),
                ),
                ("total_novedades", models.IntegerField(blank=True, null=True)),
                (
                    "total_novedades_atendidas",
                    models.IntegerField(blank=True, null=True),
                ),
                ("tickets_cerrados", models.IntegerField(blank=True, null=True)),
                (
                    "tickets_abiertos_hardware",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tickets_abiertos_software",
                    models.IntegerField(blank=True, null=True),
                ),
                ("total_copias_realizadas", models.IntegerField(blank=True, null=True)),
                (
                    "total_copias_seguridad_exitosa",
                    models.IntegerField(blank=True, null=True),
                ),
                ("ataques_ciberseguridad", models.IntegerField(blank=True, null=True)),
                ("total_equipos", models.IntegerField(blank=True, null=True)),
                (
                    "porcentaje_cumplimiento_programa",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "mantenimientos_programados",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "total_mantenimientos_realizados",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_novedades_reportadas_alta",
                    models.IntegerField(blank=True, null=True),
                ),
                ("num_novedades_atendidas", models.IntegerField(blank=True, null=True)),
                (
                    "num_novedades_reportadas_media",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_novedades_atendidas_media",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_novedades_reportadas_baja",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "num_novedades_atendidas_baja",
                    models.IntegerField(blank=True, null=True),
                ),
                ("num_reportes_supervisor", models.IntegerField(blank=True, null=True)),
                (
                    "num_atendidos_supervisor",
                    models.IntegerField(blank=True, null=True),
                ),
                ("presupuesto_ejecutado", models.FloatField(blank=True, null=True)),
                ("presupuesto_proyectado", models.FloatField(blank=True, null=True)),
                ("num_confiables", models.IntegerField(blank=True, null=True)),
                ("num_total", models.IntegerField(blank=True, null=True)),
                (
                    "calificacion_reevaluados",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "grado_satisfaccion_cliente",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("num_clientes_superior_a", models.IntegerField(blank=True, null=True)),
                ("num_clientes_evaluados", models.IntegerField(blank=True, null=True)),
                (
                    "confiabilidad_asociado_cliente",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "num_asociados_confiables",
                    models.IntegerField(blank=True, null=True),
                ),
                ("num_total_clientes", models.IntegerField(blank=True, null=True)),
                (
                    "porcentaje_nuevos_negocios",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ingresos_nuevos_negocios",
                    models.IntegerField(blank=True, null=True),
                ),
                ("meta_nuevos_negocios", models.IntegerField(blank=True, null=True)),
                (
                    "porcentaje_grado_cumplimiento",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "facturas_radicadas_tiempo",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "total_facturas_radicadas",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tiempo_promedio_cierre_pqrs",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "promedio_tiempos_cierre_pqrsrf",
                    models.FloatField(blank=True, null=True),
                ),
                ("tiempo_respuesta", models.FloatField(blank=True, null=True)),
                (
                    "porcentaje_total_pqrs",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("num_pqrsf_recibidas", models.IntegerField(blank=True, null=True)),
                ("total_servicios_periodo", models.IntegerField(blank=True, null=True)),
                (
                    "porcentaje_salidas_no_conformes",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "num_salidas_no_conformes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("total_servicios", models.IntegerField(blank=True, null=True)),
                (
                    "efectividad_ofertas_comerciales",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "num_cotizaciones_aprobadas",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "total_cotizaciones_enviados",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submenu", models.CharField(max_length=32)),
                ("valor", models.FloatField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mayor", "Mayor a"),
                            ("igual", "Igual a"),
                            ("menor", "Menor a"),
                        ],
                        default="mayor",
                        max_length=8,
                    ),
                ),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
