# Generated by Django 5.2.4 on 2025-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="calificacion_maxima",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="calificacion_promedio",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="confiabilidad_asociado_negocio",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
