# Generated by Django 5.2.4 on 2025-07-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0002_indicador_calificacion_maxima_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="eficacia_programa_capacitacion",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="promedio_capacitaciones_eficaces",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
