# Generated by Django 5.2.4 on 2025-07-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0003_indicador_eficacia_programa_capacitacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="cobertura_capacitacion",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="trabajadores_asistieron",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="trabajadores_convocados",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
