# Generated by Django 5.2.4 on 2025-07-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0004_indicador_cobertura_capacitacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="personal_contratado",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="personal_desvinculado",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="rotacion_personal",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="trabajadores_fin_mes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="trabajadores_inicio_mes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
