# Generated by Django 5.2.4 on 2025-07-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0005_indicador_personal_contratado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="evaluacion_desempeno",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="ponderacion_evaluaciones_aplicadas",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
