# Generated by Django 5.2.4 on 2025-07-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0006_indicador_evaluacion_desempeno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="tasa_ausentismo_laboral",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="total_h_ausentismo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="total_h_planificadas",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
