# Generated by Django 5.2.4 on 2025-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0007_indicador_tasa_ausentismo_laboral_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="horas_deben_trabajarse",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="horas_extras_trabajadas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="porcentaje_het",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
