# Generated by Django 5.2.4 on 2025-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0008_indicador_horas_deben_trabajarse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="num_contrataciones",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="porcentaje_tiempo_seleccion",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="tiempo_proceso_seleccion",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
