# Generated by Django 5.2.4 on 2025-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0009_indicador_num_contrataciones_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="coste_reclutamiento_externo",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="coste_reclutamiento_interno",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="costo_contratacion",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="num_contrataciones_periodo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
