# Generated by Django 5.2.4 on 2025-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0010_indicador_coste_reclutamiento_externo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="incapacidades_para_cobro_periodo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="incapacidades_radicadas_periodo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="tasa_recuperacion_incapacidades",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
