# Generated by Django 5.2.4 on 2025-07-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0011_indicador_incapacidades_para_cobro_periodo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="porcentaje_novedades_viales",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="vehiculos_con_novedad",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="vehiculos_programados",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
