# Generated by Django 5.2.4 on 2025-07-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0012_indicador_porcentaje_novedades_viales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="calificacion_cumple_totalmente",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="porcentaje_cumplimiento_instalaciones",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="sumatoria_incumplimiento",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
