# Generated by Django 5.2.4 on 2025-07-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0013_indicador_calificacion_cumple_totalmente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="num_vehiculos_exceso_velocidad",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="total_vehiculos_mes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
