# Generated by Django 5.2.4 on 2025-07-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0014_indicador_num_vehiculos_exceso_velocidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="conductores_accionan_boton_panico_evento_critico",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="sin_novedad",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="total_botones_panico_prueba",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
