# Generated by Django 5.2.4 on 2025-07-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sig",
            "0015_indicador_conductores_accionan_boton_panico_evento_critico_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="cant_riesgos_valoracion_alta_final_anio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="cant_riesgos_valoracion_alta_inicio_anio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="cantidad_riesgos_final_anio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="cantidad_riesgos_inicio_anio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="costos_directos_siniestros_viales",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="costos_indirectos_siniestros_viales",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="costos_siniestros_viales",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="cumplimiento",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="cumplimiento_actividades",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="dato_denominador_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="dato_numerador_sv",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="gestion_riesgos_viales",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="num_actividades_ejecutadas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="num_excesos_jornada",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="num_metas_alcanzadas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="num_siniestros_viales",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="num_total_actividades_programadas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="num_total_metas_definidas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="num_vehiculos_incluidos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="num_vehiculos_utilizados",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="riesgos_seguridad_vial",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indicador",
            name="total_dias_trabajados",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
