# Generated by Django 5.2.4 on 2025-07-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sig", "0017_indicador_cantidad_novedades_locativas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meta",
            name="fecha_modificacion",
        ),
        migrations.AddField(
            model_name="meta",
            name="descripcion",
            field=models.CharField(default="Sin descripción", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meta",
            name="submenu",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="meta",
            name="tipo",
            field=models.CharField(
                choices=[("mayor", ">"), ("menor", "<"), ("igual", "=")], max_length=10
            ),
        ),
    ]
