"""
Django settings for design project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import django

# Ruta base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

# Configuración rápida para desarrollo (no usar en producción)
# Clave secreta para Django
SECRET_KEY = "django-insecure-^#6(n9w$i-i@^_-pn7)n5xci7yp^%=h0p^i)da&qzw7dw(hp6i"

# Modo debug (True para desarrollo, False para producción)
DEBUG = True

# Lista de hosts permitidos
ALLOWED_HOSTS = []

# Definición de aplicaciones instaladas en el proyecto
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    "sig", # Conexion con la aplicacion sig
]

# Middleware que procesa las peticiones/respuestas
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Archivo principal de rutas del proyecto
ROOT_URLCONF = "design.urls"

# Configuración de plantillas (templates)
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],  # Directorio de plantillas personalizadas
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Configuración para aplicaciones WSGI
WSGI_APPLICATION = "design.wsgi.application"

# Configuración de la base de datos (temporal SQLite para testing)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
    }
}

# Configuración original de MySQL (comentada para testing)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'maria',  # <-- Nombre base de datos de mysql
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',
#         'PORT': '3307', #puerto muy importante 
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

# Configuración de hashers de contraseña (usando PBKDF2 para evitar dependencias)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Validadores de contraseñas para usuarios (simplificados para testing)
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 4,
        }
    },
]

# Configuración de internacionalización
LANGUAGE_CODE = "es-co"  # Idioma por defecto en español
TIME_ZONE = "UTC"        # Zona horaria
USE_I18N = True           # Habilita traducciones
USE_TZ = True             # Usa zonas horarias

# Configuración de archivos estáticos (CSS, JS, imágenes)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'sig' / 'static']

# Tipo de campo por defecto para claves primarias
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configuración de login/logout
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Algoritmos de hash para contraseñas
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


